version: "3.4"

services:
  homebox:
    image: homebox
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - COMMIT=head
        - BUILD_TIME=0001-01-01T00:00:00Z
    ports:
      - 50050:7745
    restart: unless-stopped
    environment:
      - TZ=Europe/Bratislava
    volumes:
      - /home/adamko/homebox-data/:/data
